### ISSUE TITLE
Handle product variants instead of products

### ISSUE THREAD

**Issue by Lowcost-dev** [webgriffe/SyliusClerkPlugin#1]
Hi there,

I just get in front of the problem using the search of my website using clerk and your plugin.
It must be better to use variants and send them to Clerk instead of the product. 

I'm gonna make it, and push it there or try to make a PR

What do you think ?
Why did you just choose products and not also them variants ?

**Comment by mmenozzi** [comment]
Hi there,
why do you think it's better to use variants instead of products?

Based on our experience we think it's better to send to Clerk the product and not the variant.
For example, if you do the opposite you could end up with multiple search results for a single product page which is not what a user expects in many cases.

If you need to add to your Clerk index information taken from variants you can do it by customizing the `Webgriffe\SyliusClerkPlugin\Normalizer\ProductNormalizer`.

If you still want to have variants instead of products you can replace the `ProductsQueryBuilderFactory` with a different one which returns variants. Then you can implement a custom normalizer for the variant entity.

**Comment by Lowcost-dev** [comment]
In my case, we've many products with variants and I was searching for a specific provider reference which is an option of my variants. So my users will never found them by the search engine. That's why I'm adding them to Clerk.

I'll see like you said if it's not what the user want but I think it will still be better than let them in the void.

**Comment by mmenozzi** [comment]
There's no need to send all the variants as products to Clerk.

You can add all option values belonging to a product by customizing the `Webgriffe\SyliusClerkPlugin\Normalizer\ProductNormalizer`.

This way you have only main products in Clerk and you can still search for option values.
